SKILLS_DATABASE = [
    "python",
    "java",
    "javascript",
    "typescript",
    "react",
    "angular",
    "vue",
    "node.js",
    "express",
    "next.js",
    "laravel",
    "php",
    "django",
    "flask",
    "spring",
    "c++",
    "c#",
    ".net",
    "kotlin",
    "swift",
    "flutter",
    "react native",
    "android",
    "ios",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "rest api",
    "graphql",
    "microservices",
    "html",
    "css",
    "tailwind",
    "machine learning",
    "deep learning",
    "nlp",
    "natural language processing",
    "computer vision",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "pandas",
    "numpy",
    "statistics",
    "data analysis",
    "data visualization",
    "power bi",
    "tableau",
    "excel",
    "r",
    "big data",
    "spark",
    "hadoop",
    "etl",
    "data warehousing",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "terraform",
    "jenkins",
    "ci/cd",
    "linux",
    "git",
    "bash",
    "network security",
    "cybersecurity",
    "penetration testing",
    "firewalls",
    "embedded systems",
    "iot",
    "microcontrollers",
    "rtos",
    "figma",
    "adobe xd",
    "photoshop",
    "illustrator",
    "ui/ux",
    "wireframing",
    "prototyping",
    "user research",
    "typography",
    "seo",
    "content writing",
    "copywriting",
    "social media",
    "google analytics",
    "digital marketing",
    "email marketing",
    "crm",
    "marketing strategy",
    "financial analysis",
    "financial modeling",
    "accounting",
    "econometrics",
    "business analysis",
    "requirements gathering",
    "agile",
    "scrum",
    "jira",
    "project management",
    "risk management",
    "stakeholder management",
    "communication",
    "research",
    "data mining",
    "algorithms",
    "data structures",
    "system design",
    "cloud computing",
    "testing",
]


SKILL_ALIASES = {
    "node.js": ["nodejs", "node js"],
    "next.js": ["nextjs"],
    "vue": ["vue.js", "vuejs"],
    "react": ["react.js", "reactjs"],
    "machine learning": ["ml"],
    "postgresql": ["postgres"],
    "scikit-learn": ["sklearn", "scikit learn"],
    "rest api": ["restful api", "rest apis", "restful"],
    "ci/cd": ["cicd", "continuous integration"],
    "ui/ux": ["ux/ui", "ui ux", "ux design", "ui design"],
    "gcp": ["google cloud"],
    "c#": ["csharp"],
    "power bi": ["powerbi"],
    "kubernetes": ["k8s"],
    "javascript": ["js"],
    "excel": ["ms excel", "microsoft excel"],
    "photoshop": ["adobe photoshop"],
    "illustrator": ["adobe illustrator"],
}


CAREER_MAPPING = {
    "Data Analyst": ["python", "sql", "data analysis", "excel", "data visualization", "statistics"],
    "Data Scientist": ["python", "machine learning", "statistics", "pandas", "sql", "data visualization"],
    "Data Engineer": ["python", "sql", "etl", "big data", "spark", "data warehousing"],
    "ML Engineer": ["python", "machine learning", "deep learning", "tensorflow", "scikit-learn", "docker"],
    "AI Researcher": ["python", "deep learning", "machine learning", "statistics", "pytorch", "research"],
    "AI Specialist": ["python", "machine learning", "deep learning", "nlp", "tensorflow", "cloud computing"],
    "NLP Engineer": ["python", "nlp", "natural language processing", "deep learning", "pytorch", "machine learning"],
    "Research Scientist": ["research", "statistics", "python", "r", "machine learning", "data analysis"],
    "Research Analyst": ["research", "statistics", "data mining", "python", "excel", "sql"],
    "Frontend Developer": ["javascript", "react", "html", "css", "typescript", "git"],
    "Backend Developer": ["python", "php", "laravel", "sql", "rest api", "git"],
    "Full Stack Developer": ["javascript", "react", "node.js", "sql", "rest api", "git"],
    "Software Developer": ["java", "c#", "algorithms", "data structures", "sql", "git"],
    "Software Engineer": ["java", "system design", "algorithms", "data structures", "cloud computing", "git"],
    "Mobile Developer": ["kotlin", "swift", "android", "flutter", "react native", "git"],
    "DevOps Engineer": ["docker", "kubernetes", "aws", "linux", "ci/cd", "git"],
    "Cybersecurity Analyst": ["network security", "cybersecurity", "linux", "python", "firewalls", "penetration testing"],
    "Embedded Systems Engineer": ["c++", "embedded systems", "iot", "microcontrollers", "rtos", "linux"],
    "UX Designer": ["ui/ux", "figma", "user research", "wireframing", "prototyping", "adobe xd"],
    "Graphic Designer": ["photoshop", "illustrator", "typography", "figma", "ui/ux", "communication"],
    "Digital Marketer": ["seo", "digital marketing", "social media", "content writing", "google analytics", "email marketing"],
    "Marketing Manager": ["marketing strategy", "digital marketing", "crm", "google analytics", "communication", "stakeholder management"],
    "Business Analyst": ["business analysis", "requirements gathering", "sql", "excel", "data analysis", "communication"],
    "Financial Analyst": ["financial analysis", "financial modeling", "excel", "accounting", "econometrics", "sql"],
    "Project Manager": ["project management", "agile", "scrum", "risk management", "jira", "communication"],
}


JOBS = [
    {"title": "Junior Data Analyst", "skills": ["python", "sql", "data analysis", "excel"]},
    {"title": "BI / Dashboard Analyst", "skills": ["sql", "power bi", "tableau", "excel"]},
    {"title": "Data Scientist", "skills": ["python", "machine learning", "statistics", "pandas"]},
    {"title": "Data Engineer", "skills": ["python", "sql", "aws", "spark"]},
    {"title": "ML Engineer", "skills": ["python", "machine learning", "tensorflow", "pandas"]},
    {"title": "NLP Engineer", "skills": ["python", "nlp", "pytorch", "deep learning"]},
    {"title": "React Developer", "skills": ["javascript", "react", "css", "html"]},
    {"title": "Frontend Engineer (TypeScript)", "skills": ["typescript", "react", "css", "git"]},
    {"title": "Laravel Backend Developer", "skills": ["php", "laravel", "sql", "rest api"]},
    {"title": "Python Developer", "skills": ["python", "django", "flask", "sql"]},
    {"title": "Java Backend Engineer", "skills": ["java", "spring", "microservices", "sql"]},
    {"title": "Full Stack Developer", "skills": ["javascript", "react", "node.js", "mongodb"]},
    {"title": ".NET Developer", "skills": ["c#", ".net", "sql", "git"]},
    {"title": "Android Developer", "skills": ["kotlin", "android", "java", "git"]},
    {"title": "Flutter Developer", "skills": ["flutter", "android", "ios", "git"]},
    {"title": "DevOps Engineer", "skills": ["docker", "aws", "linux", "git"]},
    {"title": "Cloud Engineer", "skills": ["aws", "terraform", "kubernetes", "linux"]},
    {"title": "Security Analyst", "skills": ["network security", "linux", "firewalls", "python"]},
    {"title": "Embedded Firmware Engineer", "skills": ["c++", "embedded systems", "microcontrollers", "rtos"]},
    {"title": "UI/UX Designer", "skills": ["figma", "ui/ux", "wireframing", "prototyping"]},
    {"title": "Graphic Designer", "skills": ["photoshop", "illustrator", "typography", "figma"]},
    {"title": "SEO & Content Specialist", "skills": ["seo", "content writing", "google analytics", "social media"]},
    {"title": "Digital Marketing Executive", "skills": ["digital marketing", "social media", "email marketing", "seo"]},
    {"title": "Business Analyst", "skills": ["business analysis", "requirements gathering", "sql", "excel"]},
    {"title": "Financial Analyst", "skills": ["financial analysis", "financial modeling", "excel", "accounting"]},
    {"title": "Project Coordinator", "skills": ["project management", "agile", "jira", "communication"]},
]
